services:
  # ts-nextcloud:
  #   image: tailscale/tailscale:latest
  #   container_name: ts-nextcloud
  #   hostname: nextcloud
  #   environment:
  #     - TS_AUTHKEY=${TS_AUTHKEY}
  #     - TS_EXTRA_ARGS=--advertise-tags=tag:container
  #     - TS_STATE_DIR=/var/lib/tailscale
  #   volumes:
  #     - /nvme/docker/nextcloud/ts/state:/var/lib/tailscale
  #     - /nvme/docker/nextcloud/ts/config:/config
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   cap_add:
  #     - net_admin
  #     - sys_module
  #   restart: unless-stopped

  nextcloud_db:
    container_name: nextcloud_db
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    volumes:
      - /nvme/docker/nextcloud/mysql:/var/lib/mysql
    networks:
      - caddy_public
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    container_name: nextcloud
    image: nextcloud:23
    restart: unless-stopped
    volumes:
      - /ssd/nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db
    networks:
      - caddy_public
    depends_on:
      - nextcloud_db

networks:
  caddy_public:
    external: true
