version: "2.1"
services:
  registry:
    image: registry.hub.docker.com/library/registry:2
    container_name: registry
    volumes:
      - /nvme/docker/registry:/var/lib/registry
    restart: unless-stopped
    networks:
      - caddy_public

networks:
  caddy_public:
    external: true