services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud
    environment:
      - PUID=1001 #nextcloud user id
      - PGID=1001
      - TZ=Europe/Paris
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ${CONFIG_DIR}:/config
      - ${DATA_DIR}:/data
    ports:
      - ${PORT}:80
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    networks:
      - nextcloud

  mariadb:
    image: mariadb:11
    container_name: nextcloud-mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DB_DIR:-./db}:/var/lib/mysql
    restart: unless-stopped
    networks:
      - nextcloud

  redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - nextcloud

networks:
  nextcloud:
    driver: bridge
