services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: florianveaux.fr # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
    env_file:
      - ./config/.env # Load API keys and credentials
    volumes:
      - ./config:/app/config # Local config directory with YAML files
      - /var/run/docker.sock:/var/run/docker.sock:ro # For docker integrations
    restart: unless-stopped
    networks:
      - caddy_public

networks:
  caddy_public:
    external: true